# Generated by Django 5.0 on 2024-04-03 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rating_App', '0002_remove_ratingmodel_rate_points_ratingmodel_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
