# Generated by Django 5.0 on 2024-04-03 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movie_App', '0011_alter_moviemodel_rating'),
        ('Rating_App', '0003_ratemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RatingModel',
        ),
    ]
