# Generated by Django 5.0 on 2024-04-03 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rating_App', '0005_alter_ratemodel_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratemodel',
            name='rating',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
