# Generated by Django 5.0 on 2024-04-03 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie_App', '0022_ratemodel_alter_moviemodel_rating'),
        ('Rating_App', '0006_alter_ratemodel_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieUserRatingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='RateModel',
        ),
    ]
