# Generated by Django 5.0 on 2024-04-03 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie_App', '0024_moviemodel_rating'),
        ('Rating_App', '0007_movieuserratingmodel_delete_ratemodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movieuserratingmodel',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Movie_App.moviemodel'),
        ),
        migrations.AddField(
            model_name='movieuserratingmodel',
            name='rate',
            field=models.FloatField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='movieuserratingmodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
