# Generated by Django 5.0 on 2024-04-03 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rating_App', '0008_movieuserratingmodel_movie_movieuserratingmodel_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieuserratingmodel',
            name='rate',
            field=models.FloatField(choices=[(1, 0.0), (2, 0.1), (3, 0.2), (4, 0.3), (5, 0.4), (6, 0.5), (7, 0.6), (8, 0.7), (9, 0.8), (10, 0.9), (11, 1.0), (12, 1.1), (13, 1.2), (14, 1.3), (15, 1.4), (16, 1.5), (17, 1.6), (18, 1.7), (19, 1.8), (20, 1.9), (21, 2.0), (22, 2.1), (23, 2.2), (24, 2.3), (25, 2.4), (26, 2.5), (27, 2.6), (28, 2.7), (29, 2.8), (30, 2.9), (31, 3.0), (32, 3.1), (33, 3.2), (34, 3.3), (35, 3.4), (36, 3.5), (37, 3.6), (38, 3.7), (39, 3.8), (40, 3.9), (41, 4.0), (42, 4.1), (43, 4.2), (44, 4.3), (45, 4.4), (46, 4.5), (47, 4.6), (48, 4.7), (49, 4.8), (50, 4.9), (51, 5.0)], null=True),
        ),
    ]
