# Generated by Django 5.0 on 2024-04-03 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rating_App', '0010_alter_movieuserratingmodel_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movieuserratingmodel',
            old_name='movie',
            new_name='movie_id',
        ),
        migrations.RenameField(
            model_name='movieuserratingmodel',
            old_name='rate',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='movieuserratingmodel',
            old_name='user',
            new_name='user_id',
        ),
    ]
