# Generated by Django 5.0 on 2024-04-03 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviemodel',
            name='genre',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='moviemodel',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='moviemodel',
            name='rating',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
