# Generated by Django 5.0 on 2024-04-03 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movie_App', '0003_genremodel_alter_moviemodel_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviemodel',
            name='genre',
        ),
    ]
