# Generated by Django 5.0 on 2024-04-03 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie_App', '0008_remove_moviemodel_rating'),
        ('Rating_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviemodel',
            name='RatingModel',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Rating_App.ratingmodel'),
        ),
    ]
