# Generated by Django 5.0 on 2024-04-03 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movie_App', '0011_alter_moviemodel_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviemodel',
            name='rating',
        ),
    ]
