# Generated by Django 5.0 on 2024-04-03 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movie_App', '0013_moviemodel_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviemodel',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='moviemodel',
            name='name',
        ),
        migrations.RemoveField(
            model_name='moviemodel',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='moviemodel',
            name='release_date',
        ),
    ]
