# Generated by Django 5.0 on 2024-04-03 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie_App', '0014_remove_moviemodel_genre_remove_moviemodel_name_and_more'),
        ('Rating_App', '0004_delete_ratingmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviemodel',
            name='genre',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Movie_App.genremodel'),
        ),
        migrations.AddField(
            model_name='moviemodel',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='moviemodel',
            name='rating',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Rating_App.ratemodel'),
        ),
        migrations.AddField(
            model_name='moviemodel',
            name='release_date',
            field=models.DateField(null=True),
        ),
    ]
