# Generated by Django 5.0 on 2024-04-03 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie_App', '0020_alter_moviemodel_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviemodel',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Movie_App.genremodel'),
        ),
    ]
