# Generated by Django 5.0 on 2024-04-03 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie_App', '0021_alter_moviemodel_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='moviemodel',
            name='rating',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Movie_App.ratemodel'),
        ),
    ]
