# Generated by Django 5.0 on 2024-04-03 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie_App', '0023_remove_moviemodel_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviemodel',
            name='rating',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Movie_App.ratemodel'),
        ),
    ]
