# Generated by Django 5.0 on 2024-04-03 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login_App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='address',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='city',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='country',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='zipcode',
        ),
    ]
