# Generated by Django 5.0 on 2024-04-03 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login_App', '0002_remove_profilemodel_address_remove_profilemodel_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilemodel',
            old_name='user',
            new_name='user_email',
        ),
    ]
