# Generated by Django 5.0 on 2024-04-03 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login_App', '0003_rename_user_profilemodel_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilemodel',
            old_name='user_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='profilemodel',
            old_name='full_name',
            new_name='name',
        ),
    ]
